# Basic Torch Operations

In [2]:
import torch
x=torch.empty(2,3,3)                # fill with garbage values
x=torch.rand(2,2)                   # fill with random values
x=torch.ones(3,3,dtype=torch.int)   # fill with ones
x=torch.zeros(3,3,dtype=torch.float16) # fill with zeros
x=torch.tensor([1,3,4])             # fill with constants
x

tensor([1, 3, 4])

In [4]:
# element wise operation

#available operations: add_,mul_,div_
x=x+x
x=torch.add(x,x)
x.add_(x)  #inplace addition


#slicing
x=torch.rand(2,4,4)
print(x[:,1,1:3])     #get all rows, only first column
print(x[0,0,0].item()) #NOTE: item() can only be used to return value of one item in tensor


tensor([[0.3038, 0.5920],
        [0.4330, 0.0238]])
0.3948076367378235


In [5]:
import numpy as np
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


# Autograd package

In [6]:
import torch
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
v=torch.tensor([0.1,1,0.001],dtype=torch.float32)
y=y*y+2
print(y)
y.backward(v)
print(x.grad)


tensor([-0.4631,  1.4813,  1.9980], requires_grad=True)
tensor([ 4.3621, 14.1197, 17.9839], grad_fn=<AddBackward0>)
tensor([0.3074, 6.9627, 0.0080])


In [8]:
#remove gradient tracking:
'''
x.requires_grad_(False)
x.detach()
with torch.no_grad():
'''
weights=torch.ones(4,requires_grad=True)
for epoch in range(4):
  model_output=(weights*3).sum()
  model_output.backward()
  print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
tensor([12., 12., 12., 12.])


# Back Propogation

In [14]:
import torch
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
for epoch in range(4):
  print(w)
  # forward pass and compute loss
  y_pred=w*x
  loss=(y_pred-y)**2
  print('loss: ',loss)
  print('gradient of w:', w.grad)

  #backward pass
  loss.backward()
  print('new gradient of w: ',w.grad)

tensor(1., requires_grad=True)
loss:  tensor(1., grad_fn=<PowBackward0>)
gradient of w: None
new gradient of w:  tensor(-2.)
tensor(1., requires_grad=True)
loss:  tensor(1., grad_fn=<PowBackward0>)
gradient of w: tensor(-2.)
new gradient of w:  tensor(-4.)
tensor(1., requires_grad=True)
loss:  tensor(1., grad_fn=<PowBackward0>)
gradient of w: tensor(-4.)
new gradient of w:  tensor(-6.)
tensor(1., requires_grad=True)
loss:  tensor(1., grad_fn=<PowBackward0>)
gradient of w: tensor(-6.)
new gradient of w:  tensor(-8.)


# Gradient Descent

In [18]:
import numpy as np
x=np.array([1,2,3,4],dtype=np.float32)
y=np.array([2,4,6,8],dtype=np.float32)
w=100

#model prediction

def forward(x):
  return w*x


#loss
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()

#gradient
def gradient(x,y,y_pred):
  return np.dot(2*x,y_pred-y).mean()

print(f'prediction before training f(5): {forward(5):.3f}')

#Training
lr=0.01
iter=20

for epoch in range(iter):
  y_pred=forward(x)
  l=loss(y,y_pred)
  dw=gradient(x,y,y_pred)

  #update weights

  w-=lr*dw
  if epoch % 1 ==0:
    print(f'epoch: {epoch+1}; w = {w:.3f}; loss = {l:.8f}')
    
  print(f'f(5): {forward(5):.3f}')

prediction before training f(5): 500.000
epoch: 1; w = 41.200; loss = 72030.00000000
f(5): 206.000
epoch: 2; w = 17.680; loss = 11524.80078125
f(5): 88.400
epoch: 3; w = 8.272; loss = 1843.96801758
f(5): 41.360
epoch: 4; w = 4.509; loss = 295.03491211
f(5): 22.544
epoch: 5; w = 3.004; loss = 47.20556259
f(5): 15.018
epoch: 6; w = 2.401; loss = 7.55289316
f(5): 12.007
epoch: 7; w = 2.161; loss = 1.20846248
f(5): 10.803
epoch: 8; w = 2.064; loss = 0.19335407
f(5): 10.321
epoch: 9; w = 2.026; loss = 0.03093682
f(5): 10.128
epoch: 10; w = 2.010; loss = 0.00494985
f(5): 10.051
epoch: 11; w = 2.004; loss = 0.00079199
f(5): 10.021
epoch: 12; w = 2.002; loss = 0.00012671
f(5): 10.008
epoch: 13; w = 2.001; loss = 0.00002027
f(5): 10.003
epoch: 14; w = 2.000; loss = 0.00000324
f(5): 10.001
epoch: 15; w = 2.000; loss = 0.00000052
f(5): 10.001
epoch: 16; w = 2.000; loss = 0.00000008
f(5): 10.000
epoch: 17; w = 2.000; loss = 0.00000001
f(5): 10.000
epoch: 18; w = 2.000; loss = 0.00000000
f(5): 10.0

In [20]:
import torch
x=torch.tensor([1,2,3,4],dtype=torch.float32)
y=torch.tensor([2,4,6,8],dtype=torch.float32)
w=torch.tensor(0.0,requires_grad=True,dtype=torch.float32)

#model prediction

def forward(x):
  return w*x


#loss
def loss(y,y_pred):
  return ((y_pred-y)**2).mean()

#gradient
def gradient(x,y,y_pred):
  return np.dot(2*x,y_pred-y).mean()

print(f'prediction before training f(5): {forward(5):.3f}')

#Training
lr=0.01
iter=20

for epoch in range(iter):
  y_pred=forward(x)
  l=loss(y,y_pred)
  l.backward()

  #update weights
  with torch.no_grad():
    w-=lr*w.grad

  w.grad.zero_()
  if epoch % 2 ==0:
    print(f'epoch: {epoch+1}; w = {w:.3f}; loss = {l:.8f}')
    
  print(f'f(5): {forward(5):.3f}')

prediction before training f(5): 0.000
epoch: 1; w = 0.300; loss = 30.00000000
f(5): 1.500
f(5): 2.775
epoch: 3; w = 0.772; loss = 15.66018772
f(5): 3.859
f(5): 4.780
epoch: 5; w = 1.113; loss = 8.17471695
f(5): 5.563
f(5): 6.229
epoch: 7; w = 1.359; loss = 4.26725292
f(5): 6.794
f(5): 7.275
epoch: 9; w = 1.537; loss = 2.22753215
f(5): 7.684
f(5): 8.031
epoch: 11; w = 1.665; loss = 1.16278565
f(5): 8.327
f(5): 8.578
epoch: 13; w = 1.758; loss = 0.60698116
f(5): 8.791
f(5): 8.972
epoch: 15; w = 1.825; loss = 0.31684780
f(5): 9.126
f(5): 9.257
epoch: 17; w = 1.874; loss = 0.16539653
f(5): 9.369
f(5): 9.464
epoch: 19; w = 1.909; loss = 0.08633806
f(5): 9.544
f(5): 9.612


# Training pipeline

In [36]:
import torch
import torch.nn as nn

#input
x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)

#expected output
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

#test input
test=torch.tensor([5],dtype=torch.float32)

n_samples,n_features=x.shape
input_size=n_features
output_size=n_features


#model
class LinearRegression(nn.Module):
  def __init__(self,input_dim,output_dim):
    super(LinearRegression,self).__init__()
    self.lin=nn.Linear(input_dim,output_dim)

  def forward(self,x):
    return self.lin(x)
  
model=LinearRegression(input_size,output_size)


#loss function to calculate difference between predicted and current
loss=nn.MSELoss()

#optimiser to minimise given loss on model by changing model weights
optimizer=torch.optim.SGD(model.parameters(),lr=lr)


print(f'prediction before training f(5): {forward(test).item():.3f}')

#Training
lr=0.01
iter=20


for epoch in range(iter):
  y_pred=model.forward(x)
  l=loss(y,y_pred)
  l.backward()
  optimizer.step()
  optimizer.zero_grad()
  if epoch % 2 ==0:
    [w,b]=model.parameters()

    print(f'epoch: {epoch+1}; w = {w[0][0]}; loss = {l:.8f}')
    print(f'f(5): {forward(test).item():.3f}')

prediction before training f(5): 14.797
epoch: 1; w = 0.06583143025636673; loss = 38.52408600
f(5): 0.329
epoch: 3; w = 0.585242748260498; loss = 18.59125519
f(5): 2.926
epoch: 5; w = 0.9460858106613159; loss = 8.99372101
f(5): 4.730
epoch: 7; w = 1.1968990564346313; loss = 4.37230921
f(5): 5.984
epoch: 9; w = 1.3713624477386475; loss = 2.14674592
f(5): 6.857
epoch: 11; w = 1.4928457736968994; loss = 1.07471204
f(5): 7.464
epoch: 13; w = 1.5775647163391113; loss = 0.55807149
f(5): 7.888
epoch: 15; w = 1.6367710828781128; loss = 0.30884147
f(5): 8.184
epoch: 17; w = 1.6782723665237427; loss = 0.18836650
f(5): 8.391
epoch: 19; w = 1.7074857950210571; loss = 0.12988871
f(5): 8.537


In [35]:
import torch
import torch.nn as nn

#input
x=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)

#expected output
y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

#test input
test=torch.tensor([5],dtype=torch.float32)

n_samples,n_features=x.shape
input_size=n_features
output_size=n_features


#model
class LinearRegression(nn.Module):
  def __init__(self,input_dim,output_dim):
    super(LinearRegression,self).__init__()
    self.lin=nn.Linear(input_dim,output_dim)

  def forward(self,x):
    return self.lin(x)
  
model=LinearRegression(input_size,output_size)


#loss function to calculate difference between predicted and current
loss=nn.MSELoss()

#optimiser to minimise given loss on model by changing model weights
optimizer=torch.optim.SGD(model.parameters(),lr=lr)


print(f'prediction before training f(5): {forward(test).item():.3f}')

#Training
lr=0.01
iter=20


for epoch in range(iter):
  y_pred=model.forward(x)
  l=loss(y,y_pred)
  l.backward()
  optimizer.step()
  if epoch % 2 ==0:
    [w,b]=model.parameters()

    print(f'epoch: {epoch+1}; w = {w[0][0]}; loss = {l:.8f}')
    print(f'f(5): {forward(test).item():.3f}')

prediction before training f(5): 12.542
epoch: 1; w = -0.17460355162620544; loss = 39.85884857
f(5): -0.873
epoch: 3; w = 1.2750879526138306; loss = 11.27946281
f(5): 6.375
epoch: 5; w = 2.9052915573120117; loss = 3.46660089
f(5): 14.526
epoch: 7; w = 3.6801609992980957; loss = 33.19767380
f(5): 18.401
epoch: 9; w = 3.1146790981292725; loss = 36.48851013
f(5): 15.573
epoch: 11; w = 1.5850011110305786; loss = 6.20999908
f(5): 7.925
epoch: 13; w = 0.08749580383300781; loss = 7.42359161
f(5): 0.437
epoch: 15; w = -0.39926877617836; loss = 37.45241547
f(5): -1.996
epoch: 17; w = 0.45882153511047363; loss = 31.64179230
f(5): 2.294
epoch: 19; w = 2.137280225753784; loss = 2.41944838
f(5): 10.686


# linear regression

In [11]:
import torch
import torch.nn as nn

import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

x_numpy,y_numpy=datasets.make_regression(n_samples=100,n_features=1,noise=20,random_state=1)
X=torch.from_numpy(x_numpy.astype(np.float32))
Y=torch.from_numpy(y_numpy.astype(np.float32))
print(X.shape,Y.shape)
Y=Y.view(Y.shape[0],1)

n_samples,n_features=X.shape

input_size=1
output_size=1

#model
model=nn.Linear(input_size,output_size)

#loss and optimier

lr=0.01
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=lr)

#training loop

for epoch in range(1000):
  y_pred=model(X)
  loss=criterion(Y,y_pred)
  loss.backward()

  optimizer.step()
  optimizer.zero_grad()

  if(epoch%5==0):
    print(f'epoch: {epoch+1}; loss: {loss}')


#plot

predicted=model(X).detach().numpy()
plt.plot(X.numpy(),predicted,'r')
plt.plot(X.numpy(),Y.numpy(),'bo')
plt.show()

torch.Size([100, 2]) torch.Size([100])


RuntimeError: ignored

# Logistic regression

In [32]:
import torch
import torch.nn as nn
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

bc=datasets.load_breast_cancer()
X,y=bc.data,bc.target

n_samples, n_features=X.shape

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)


# scale

sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

X_train=torch.from_numpy(X_train.astype(np.float32))
X_test=torch.from_numpy(X_test.astype(np.float32))

y_train=torch.from_numpy(y_train.astype(np.float32))
y_test=torch.from_numpy(y_test.astype(np.float32))

y_train=y_train.view(y_train.shape[0],1)
y_test=y_test.view(y_test.shape[0],1)


class LogisticRegression(nn.Module):
  
  def __init__(self, n_input_features):
    super(LogisticRegression,self).__init__()
    self.linear=nn.Linear(n_input_features,1)

  def forward(self,x):
    y_predicted=torch.sigmoid(self.linear(x))
    return y_predicted

model=LogisticRegression(n_features)
lr=0.01
criterion=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=lr)
EPOCHS = 100

for epoch in range(EPOCHS):
  y_pred=model(X_train)
  l=criterion(y_pred,y_train)
  l.backward()
  with torch.no_grad():
    lo=criterion(model(X_test),y_test)
  optimizer.step()
  optimizer.zero_grad()



  if epoch % 5 == 0:
    print(f'epoch: {epoch}; train_loss: {l.item():.4f}; val_loss: {lo.item():.4f};')


with torch.no_grad():
  y_predicted=model(X_test)
  y_class=y_predicted.round()
  acc=y_class.eq(y_test).sum() / float(y_test.shape[0])
  print(f'accuracy: {acc.item():.4f}')

epoch: 0; train_loss: 0.6189; val_loss: 0.6197;
epoch: 5; train_loss: 0.5483; val_loss: 0.5596;
epoch: 10; train_loss: 0.4951; val_loss: 0.5135;
epoch: 15; train_loss: 0.4537; val_loss: 0.4770;
epoch: 20; train_loss: 0.4206; val_loss: 0.4474;
epoch: 25; train_loss: 0.3935; val_loss: 0.4229;
epoch: 30; train_loss: 0.3710; val_loss: 0.4023;
epoch: 35; train_loss: 0.3519; val_loss: 0.3846;
epoch: 40; train_loss: 0.3355; val_loss: 0.3693;
epoch: 45; train_loss: 0.3213; val_loss: 0.3559;
epoch: 50; train_loss: 0.3088; val_loss: 0.3440;
epoch: 55; train_loss: 0.2977; val_loss: 0.3334;
epoch: 60; train_loss: 0.2878; val_loss: 0.3238;
epoch: 65; train_loss: 0.2789; val_loss: 0.3152;
epoch: 70; train_loss: 0.2708; val_loss: 0.3073;
epoch: 75; train_loss: 0.2635; val_loss: 0.3001;
epoch: 80; train_loss: 0.2568; val_loss: 0.2934;
epoch: 85; train_loss: 0.2506; val_loss: 0.2873;
epoch: 90; train_loss: 0.2449; val_loss: 0.2816;
epoch: 95; train_loss: 0.2397; val_loss: 0.2763;
accuracy: 0.9474


# DataLoading

In [ ]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

class WineDataset(Dataset):
  def __init__(self):
    #data loading
    xy=np.loadtxt('/content/wine.csv',delimiter=",",dtype=np.float32,skiprows=1)

    self.x=torch.from_numpy(xy[:,1:])
    self.y=torch.from_numpy(xy[:,[0]]) #n_Samples,1
    self.n_samples=xy.shape[0]
  def __getitem__(self,index):
    # dataset[0]
    return self.x[index],self.y[index]

  def __len__(self):
    #len(dataset)
    return self.n_samples

dataset=WineDataset()
dataloader=DataLoader(dataset=dataset,batch_size=4,shuffle=True,num_workers=2)

#training loop

num_epochs=1
total_samples=len(dataset)
batch_size=4
n_iterations=math.ceil(total_samples/batch_size)

for epoch in range(num_epochs):
  for i,(inputs,labels) in enumerate(dataloader):
    print(i)
    print(inputs)
    print(labels)

# TorchVision Transform

In [47]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

class WineDataset(Dataset):

  def __init__(self,transform=None):
    #data loading
    xy=np.loadtxt('/content/wine.csv',delimiter=",",dtype=np.float32,skiprows=1)

    self.x=xy[:,1:]
    self.y=xy[:,[0]] #n_Samples,1
    self.n_samples=xy.shape[0]
    self.transform=transform
  
  def __getitem__(self,index):
    # dataset[0]
    sample= self.x[index],self.y[index]
    if self.transform:
      sample=self.transform(sample)
    return sample



  def __len__(self):
    #len(dataset)
    return self.n_samples


class ToTensor:
  def __call__(self,sample):
    inputs,targets=sample
    return torch.from_numpy(inputs),torch.from_numpy(targets)


class MulTransform:
  def __init__(self,factor):
    self.factor=factor
  
  def __call__(self,sample):
    inputs,target=sample
    return inputs*self.factor,target*self.factor
  
dataset=WineDataset(transform=ToTensor())
composed=torchvision.transforms.Compose([ToTensor(),MulTransform(2)])
datanew=WineDataset(transform=composed)
print(datanew[0])

(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03]), tensor([2.]))


# Softmax and Cross-Entropy

In [57]:
import torch
import torch.nn as nn
import numpy as np
loss=nn.CrossEntropyLoss()

Y=torch.tensor([0])
y_pred_bad=torch.tensor([[24.1,43.0,1.0]])
y_pred_good=torch.tensor([[43.0,0.1,1.0]])

print(loss(y_pred_bad,Y).item())
print(loss(y_pred_good,Y).item())

_,pred=torch.max(y_pred_bad,1)
print(pred)

18.899999618530273
0.0
tensor([1])


In [59]:
class NeuralNet(nn.Module):
  
  def __init__ (self,input_size,hidden_size,num_classes):
    super(NeuralNet,self).__init__()
    self.linear1=nn.Linear(input_size,hidden_size)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(hidden_size,num_classes)

  def forward(self,x):
    out=self.linear1(x)
    out=self.relu(out)
    out=self.linear2(out)
    return out

model=NeuralNet(input_size=28*28,hidden_size=5,num_classes=3)
losses=nn.CrossEntropyLoss()


# Feed Forward

In [67]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

device=torch.device('cpu')

#hyper parameter
input_size=784 #28*28
hidden_size=100
num_classes=10
num_epochs=2
batch_size=100
learning_rate=0.001

#data

train_dataset=torchvision.datasets.MNIST(root='./data',train=True,transform=transforms.ToTensor(),download=True)
test_dataset=torchvision.datasets.MNIST(root='./data',train=False,transform=transforms.ToTensor())

train_loader=torch.utils.data.DataLoader(dataset=train_dataset,batch_size=batch_size,shuffle=True)

test_loader=torch.utils.data.DataLoader(dataset=test_dataset,batch_size=batch_size)

class NeuralNet(nn.Module):
  
  def __init__ (self,input_size,hidden_size,num_classes):
    super(NeuralNet,self).__init__()
    self.linear1=nn.Linear(input_size,hidden_size)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(hidden_size,num_classes)

  def forward(self,x):
    out=self.linear1(x)
    out=self.relu(out)
    out=self.linear2(out)
    return out

model=NeuralNet(input_size,hidden_size,num_classes)
losses=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)


#training loop
n_total_steps=len(train_loader)
for epoch in range(num_epochs):
  for i,(images,labels) in enumerate(train_loader):
    images=images.reshape(-1,28*28)
    
    output=model(images)
    l=loss(output,labels)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

    if(i+1%100==0):
      print(f'Epoch: {epoch}; step: {i}; loss: {l.item()}')

with torch.no_grad():
  n_correct=0.0
  n_samples=0.0
  for images,labels in test_loader:
    images=images.reshape(-1,28*28)
    output=model(images)
    _,pred=torch.max(output,1)
    n_correct+=pred.eq(labels).sum().item()
    n_samples+=labels.shape[0]

print('accuracy: ',n_correct/n_samples)

accuracy:  0.955
